baseURL: http://example.org.
languageCode: en-us
title: Ashwath

theme: "toha"

languages:
  en:
    languageName: English
    weight: 1

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
  - HTML
  - RSS
  - JSON

# Enable Google Analytics
googleAnalytics: UA-122321624-2

# Enable global emoji support
enableEmoji: true

params:
  # Background image of the landing page
  background: images/default-background.jpg
  logo:
    main: images/main-logo.png
    inverted: images/inverted-logo.png
    favicon: images/favicon.png
  
  enableBlogPost: true
  
  enableTOC: true
  
  features:
    # Enable and configure portfolio
    portfolio:
      enable: true
    # Enable and configure blog posts
    blog:
      enable: true
    # Enable & configure "Notes" features
    notes:
      enable: true
    
    # author:
    #   enable:true
